### ISSUE TITLE
BottomSheetBarController.collapse & .expand() didn't work sometimes

### ISSUE THREAD

**Issue by moehrlef** [mhrst/bottom_sheet_bar#5]
Dear developers,

i have integrated the bottom sheet bar expect of using a ListView instead of a CustomScrollView exactly like in the example. Unfortunately after 2-3 times of triggering the .collapse() and .expand() method they didn't react anymore and as a result the sheet will not open or close by triggering them. Open and close with drag and swipe is possible.

Does someone else having this issue?

**Comment by mhrst** [comment]
It's possible the animation controller isn't behaving properly. I will test the example with a ListView to see if I can reproduce.

**Comment by mhrst** [comment]
I haven't been able to reproduce this. One thing I noticed in testing: `isExpanded` and `isCollapsed` are not always accurate. Sometimes the [AnimationController] gets stuck at values close to 0 or 1 (for example: 0.99999 when it is fully expanded).

If you're using `isExpanded` or `isCollapsed` to determine whether to `expand()` or `collapse()`, then you might not be getting the expected behavior.

Looking into a better measure of collapsed or expanded state...

**Comment by mhrst** [comment]
Version 2.1.0 is now available. Part of it was resolving #11 and the changes to collapse and expand may have resolved this for you.

Let me know if you still see this issue in 2.1.0, thanks!

**Comment by mhrst** [comment]
Please open a new ticket if this issue is still being observed, thanks!
